spring:
  application:
    name: microservice-api-gateway
  session:
    store-type: redis
server: 
  port: 8050
eureka: 
  client: 
    healthcheck:
      enabled: true
    serviceUrl: 
      defaultZone: http://10.100.3.129:8761/eureka/
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    app-microservice:
      path: /api/**
      service-id: app-microservice
      sensitiveHeaders: 
  #ignored-services: microservice-front-provider   #不发布此服务，内部也无法访问
redis:
  hostname: 10.100.3.127
  port: 6379
robbin:
  ReadTimeout: 60000
  ConnectTimeout: 60000
kaptcha:  
  session:  
    key: kaptcha.code  
  #border: no  
  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy  
  obscurificator:  
    impl: com.google.code.kaptcha.impl.WaterRipple  
  #不要噪点  
  noise:  
    impl: com.google.code.kaptcha.impl.NoNoise  
  image:  
    width: 90  
    height: 33  
  textproducer:  
    font:  
      size: 25  
      color: black  
    char:  
      length: 4  
      space: 5  
  #和登录框背景颜色一致  
  background:  
    clear:  
      from: 247,247,247 
      to: 247,247,247 
